// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS';
export const CREATE_NEW_USER_FAIL = 'CREATE_NEW_USER_FAIL';
export const FETCH_USER_DB_INFO = 'FETCH_USER_DB_INFO';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SET_USER_AUTH_INFO = 'SET_USER_AUTH_INFO';

// Game Data
export const FETCH_BEER_INFO = 'FETCH_BEER_INFO';
export const FETCH_GAME_INFO = 'FETCH_GAME_INFO';
